wandb_version: 1

return_dict:
  desc: null
  value: true
output_hidden_states:
  desc: null
  value: false
output_attentions:
  desc: null
  value: false
torchscript:
  desc: null
  value: false
use_bfloat16:
  desc: null
  value: false
pruned_heads:
  desc: null
  value: {}
tie_word_embeddings:
  desc: null
  value: true
is_encoder_decoder:
  desc: null
  value: false
is_decoder:
  desc: null
  value: false
add_cross_attention:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
max_length:
  desc: null
  value: 20
min_length:
  desc: null
  value: 0
do_sample:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
num_beams:
  desc: null
  value: 1
num_beam_groups:
  desc: null
  value: 1
diversity_penalty:
  desc: null
  value: 0.0
temperature:
  desc: null
  value: 1.0
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
repetition_penalty:
  desc: null
  value: 1.0
length_penalty:
  desc: null
  value: 1.0
no_repeat_ngram_size:
  desc: null
  value: 0
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
bad_words_ids:
  desc: null
  value: null
num_return_sequences:
  desc: null
  value: 1
chunk_size_feed_forward:
  desc: null
  value: 0
output_scores:
  desc: null
  value: false
return_dict_in_generate:
  desc: null
  value: false
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
architectures:
  desc: null
  value:
  - BertForMaskedLM
finetuning_task:
  desc: null
  value: null
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
tokenizer_class:
  desc: null
  value: null
prefix:
  desc: null
  value: null
bos_token_id:
  desc: null
  value: null
pad_token_id:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value: null
sep_token_id:
  desc: null
  value: null
decoder_start_token_id:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
_name_or_path:
  desc: null
  value: kykim/bert-kor-base
embedding_size:
  desc: null
  value: 768
directionality:
  desc: null
  value: bidi
model_type:
  desc: null
  value: bert
pooler_fc_size:
  desc: null
  value: 768
pooler_num_attention_heads:
  desc: null
  value: 12
pooler_num_fc_layers:
  desc: null
  value: 3
pooler_size_per_head:
  desc: null
  value: 128
pooler_type:
  desc: null
  value: first_token_transform
vocab_size:
  desc: null
  value: 42000
hidden_size:
  desc: null
  value: 768
num_hidden_layers:
  desc: null
  value: 12
num_attention_heads:
  desc: null
  value: 12
hidden_act:
  desc: null
  value: gelu
intermediate_size:
  desc: null
  value: 3072
hidden_dropout_prob:
  desc: null
  value: 0.1
attention_probs_dropout_prob:
  desc: null
  value: 0.1
max_position_embeddings:
  desc: null
  value: 512
type_vocab_size:
  desc: null
  value: 2
initializer_range:
  desc: null
  value: 0.02
layer_norm_eps:
  desc: null
  value: 1.0e-12
gradient_checkpointing:
  desc: null
  value: false
position_embedding_type:
  desc: null
  value: absolute
use_cache:
  desc: null
  value: true
transformers_version:
  desc: null
  value: 4.4.0
output_dir:
  desc: null
  value: ./.checkpoints
overwrite_output_dir:
  desc: null
  value: false
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: None
do_predict:
  desc: null
  value: false
evaluation_strategy:
  desc: null
  value: epoch
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 96
per_device_eval_batch_size:
  desc: null
  value: 96
per_gpu_train_batch_size:
  desc: null
  value: None
per_gpu_eval_batch_size:
  desc: null
  value: None
gradient_accumulation_steps:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: None
learning_rate:
  desc: null
  value: 5.0e-05
weight_decay:
  desc: null
  value: 0.01
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 2
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: linear
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 800
logging_dir:
  desc: null
  value: runs/Oct09_20-27-45_kwonyonggeun
logging_strategy:
  desc: null
  value: steps
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 40
save_strategy:
  desc: null
  value: steps
save_steps:
  desc: null
  value: 2000
save_total_limit:
  desc: null
  value: None
no_cuda:
  desc: null
  value: false
seed:
  desc: null
  value: 42
fp16:
  desc: null
  value: true
fp16_opt_level:
  desc: null
  value: O1
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
tpu_num_cores:
  desc: null
  value: None
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: false
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: 40
dataloader_num_workers:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: ./.checkpoints
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
label_names:
  desc: null
  value: None
load_best_model_at_end:
  desc: null
  value: true
metric_for_best_model:
  desc: null
  value: loss
greater_is_better:
  desc: null
  value: false
ignore_data_skip:
  desc: null
  value: false
sharded_ddp:
  desc: null
  value: '[]'
deepspeed:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
report_to:
  desc: null
  value: '[''tensorboard'', ''wandb'']'
ddp_find_unused_parameters:
  desc: null
  value: None
dataloader_pin_memory:
  desc: null
  value: true
skip_memory_metrics:
  desc: null
  value: false
_n_gpu:
  desc: null
  value: 1
train_batch_size:
  desc: null
  value: 96
eval_batch_size:
  desc: null
  value: 96
_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.4.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696850866.972987
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 53
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.8.17
      5: 0.15.8
      6: 4.4.0
      8:
      - 5
